matrix:
  include:
  - os: linux
    dist: bionic
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-7
        - libgmp-dev
        - libmpfr-dev
        - libmpc-dev
        - verilator
        - iverilog
        - ngspice
    env:
    - CC=gcc-7
    - CXX=g++-7
  - os: osx
    osx_image: xcode10.3
    addons:
      homebrew:
        packages:
          - verilator
          - icarus-verilog
          - ngspice
          - fftw
        update: true

# python managed by conda until 3.7 available
# python:
# - '3.6'

install:
# install conda for py 3.7
- |
  if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    wget https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh
  else
    # install conda for py 3.7
    wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  fi
- chmod +x miniconda.sh
- ./miniconda.sh -b -p $TRAVIS_BUILD_DIR/miniconda
- export PATH=$TRAVIS_BUILD_DIR/miniconda/bin:$PATH
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
- conda create -q -n test-env python=3.7.3
- source activate test-env
- conda install pip
# End install conda
- |
  if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    # speed up the build process until it's fixed at z3
    # see https://github.com/Z3Prover/z3/issues/2800
    pip install https://github.com/Z3Prover/z3/releases/download/Nightly/z3_solver-4.8.8.0-py2.py3-none-macosx_10_14_x86_64.whl
    pip install kratos==0.0.25
  fi
- pip install pytest-cov pytest-codestyle
- pip install mantle>=2.0.0  # for tests.common
- pip install -e .
# Begin setup CoSA dependencies
- |
  if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
    pysmt-install --msat --confirm-agreement
  fi
- pysmt-install --z3 --confirm-agreement
- export PYTHONPATH="/home/travis/.smt_solvers/python-bindings-3.7:${PYTHONPATH}"
- export LD_LIBRARY_PATH="/home/travis/.smt_solvers/python-bindings-3.7:${LD_LIBRARY_PATH}"
- pysmt-install --check
# End setup CoSA dependencies

script:
- pytest --pycodestyle --cov-report=xml --cov=fault tests/ -v -r s
- bash <(curl -s https://codecov.io/bash)
deploy:
  provider: script
  script: /bin/bash .travis/deploy.sh
  skip_cleanup: true
  on:
    tags: true
    branch: master
