name: Linux Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      shell: bash
      run: |
          sudo apt install -y verilator libgmp-dev libmpfr-dev libmpc-dev iverilog
          verilator --version
    - name: Install pono
      shell: bash
      env: 
          CC: gcc-8
          CXX: g++-8
      run: |
          wget https://github.com/rdaly525/coreir/releases/download/v0.1.50/coreir-linux.tar.gz
          tar -xzf coreir-linux.tar.gz
          cd coreir-linux
          sudo make install 
          cd ../
          pip install Cython==0.29 --install-option="--no-cython-compile"
          git clone https://github.com/leonardt/pono
          cd pono
          ./travis-scripts/setup-msat.sh --auto-yes
          ./contrib/setup-bison.sh
          ./contrib/setup-flex.sh
          ./contrib/setup-btor2tools.sh
          ./travis-scripts/download-cvc4.sh
          ./contrib/setup-smt-switch.sh --with-msat --cvc4-home=./deps/CVC4 --python
          pip install -e ./deps/smt-switch/build/python
          ./configure.sh --with-msat --python --with-coreir-extern
          cd build && make -j2 pono-lib pono && cd ../
          pip install -e ./build/python
          cd ..

    - name: Install Python packages
      shell: bash -l {0}
      run: |
          pip install "pytest<6"
          pip install pytest-cov pytest-pycodestyle
          pip install mantle>=2.0.0  # for tests.common
          pip install vcdvcd decorator kratos
          pip install .

    - name: Pytest
      shell: bash -l {0}
      run: |
        export LD_LIBRARY_PATH=/usr/lib:$LD_LIBRARY_PATH
        pytest --pycodestyle --cov-report=xml --cov=fault tests/ -v -r s
    - name: Coverage
      shell: bash -l {0}
      run: |
        bash <(curl -s https://codecov.io/bash)

